name: autocomplete_ui
version: 0.1.1+2
author: Herbert Poul <herbert.poul@gmail.com>
description: A simple Web Component which provides an input text field with  autocompletion drop down.
homepage: https://github.com/hpoul/dart-autocomplete-ui
dependencies:
  browser: any
  html5lib: any
  logging: any
  polymer: any
transformers:
- polymer:
    entry_points: 
      - web/example.html

#  js: any
#  unittest: any
