name: autocomplete_ui
version: 0.2.0+2
author: Herbert Poul <herbert.poul@gmail.com>
description: A simple Polymer Element which provides an input text field with autocompletion drop down.
homepage: https://github.com/hpoul/dart-autocomplete-ui
dependencies:
  browser: any
  html5lib: any
  logging: any
  polymer: ">=0.11.0 <0.16.0"
transformers:
- polymer:
    entry_points: 
      - web/example.html
