name: autocomplete_ui
version: 0.0.6+4
author: Herbert Poul <herbert.poul@gmail.com>
description: A simple Web Component which provides an input text field with  autocompletion drop down.
homepage: https://github.com/hpoul/dart-autocomplete-ui
dependencies:
  browser: any
  html5lib: any
  logging: any
  web_ui: '>=0.4.20'

#  js: any
#  unittest: any