// Auto-generated from example.html.
// DO NOT EDIT.

library example_html;

import 'dart:html' as autogenerated;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;

import 'dart:html';

import 'dart:async';

import 'package:autocomplete_ui/input_autocomplete.dart';

import 'lib/input_autocomplete_component_proxy.dart';


// Original code
var exampleData = new ExampleData();
var exampleDatasource = new ExampleDatasource(exampleData.autocompleteChoices);

void main() {
}


class ExampleData {
  
  List<String> get autocompleteChoices {
    return ['Test 1', 'Test 2', 'Misc', 'Abcdef', 'Haha', 'Lorem Ipsum', 'Testing 3']..sort();
  }
}




class ExampleDatasource extends SimpleStringDatasource {
  ExampleDatasource(givenChoices) : super(givenChoices);

  Future<Iterable<AutocompleteChoice>> query(String query) {
    var completer = new Completer<Iterable<AutocompleteChoice>>();
    var future = super.query(query);
    window.setTimeout(() {
      future.then((coll) => completer.complete(coll));
    }, 1000);
    return completer.future;
  }
}


// Additional generated code
void init_autogenerated() {
  var _root = autogenerated.document.body;
  var __e0, __e1;

  var __t = new autogenerated.Template(_root);
  __e0 = _root.query('#__e-0');
  __t.oneWayBind(() => (exampleData.autocompleteChoices), (e) { __e0.xtag.choices = e; }, false);
  new InputAutocompleteComponentProxy.forElement(__e0);
  __t.component(__e0);
  __e1 = _root.query('#__e-1');
  __t.oneWayBind(() => (exampleDatasource), (e) { __e1.xtag.datasource = e; }, false);
  new InputAutocompleteComponentProxy.forElement(__e1);
  __t.component(__e1);
  

  __t.create();
  __t.insert();
}
