// Auto-generated from input_autocomplete.html.
// DO NOT EDIT.

library x_input_autocomplete;

import 'dart:html' as autogenerated_html;
import 'dart:web_audio' as autogenerated_audio;
import 'dart:svg' as autogenerated_svg;
import 'package:web_ui/web_ui.dart' as autogenerated;

import 'package:autocomplete_ui/input_autocomplete.dart';

import 'dart:html';

class InputAutocompleteComponentProxy extends InputAutocompleteComponent {
  
  /** Autogenerated from the template. */
  
  /**
  * Shadow root for this component. We use 'var' to allow simulating shadow DOM
  * on browsers that don't support this feature.
  */
  var _root;
  autogenerated_html.UnknownElement __e7;
  
  List<autogenerated.WatcherDisposer> __stoppers1;
  
  autogenerated_html.Node _endPosition__e7;
  
  bool _isVisible__e7 = false;
  
  autogenerated_html.UListElement __e6;
  
  autogenerated_html.UnknownElement __e5;
  
  List<autogenerated.WatcherDisposer> __stoppers2_1;
  
  List<Function> _removeChild__e5 = [];
  
  autogenerated_html.Node _endPosition__e5;
  
  autogenerated_html.InputElement __e8;
  
  autogenerated_html.EventListener __listener__e8_blur_6;
  
  autogenerated_html.EventListener __listener__e8_focus_7;
  
  autogenerated_html.EventListener __listener__e8_keyDown_8;
  
  autogenerated_html.EventListener __listener__e8_keyUp_9;
  
  InputAutocompleteComponentProxy.forElement(e) : super.forElement(e);
  
  void created_autogenerated() {
    _root = createShadowRoot();
    
    _root.innerHtml = '''
    
    <div class="autocomplete-wrapper">
    <template id="__e-7" style="display:none"></template>
    <input type="text" id="__e-8">
    </div>
    <style>
    .autocomplete-wrapper input {
      border: 1px solid black;
      padding: 3px;
    }
    .autocomplete-content {
      //display: none;
      position: absolute;
      border: 1px solid black;
      padding: 0px;
      margin: 0px;
      background-color: #fff;
      overflow-x: scroll;
    }
    .autocomplete-content li {
      list-style-type: none;
      padding: 2px;
      margin: 0px;
      margin-top: 2px;
      background-color: #fafafa;
    }
    .autocomplete-content li.focused {
      background-color: #ddd;
    }
    .autocomplete-content div {
      padding: 0px;
      margin: 0px;
    }
    </style>
    ''';
    __e7 = _root.query('#__e-7');
    __stoppers1 = [];
    __e8 = _root.query('#__e-8');
    
  }
  
  void inserted_autogenerated() {
    _endPosition__e7 = __e7;
    
    __stoppers1.add(autogenerated.watchAndInvoke(() => inputHasFocus && matches != null, (__e) {
      bool showNow = __e.newValue;
      if (_isVisible__e7 && !showNow) {
        _isVisible__e7 = false;
        
        __e6 = null;
        (__stoppers2_1..forEach((s) => s())).clear();
        _endPosition__e5 = autogenerated.removeNodes(__e5, _endPosition__e5);
        for (var remover in _removeChild__e5) remover();
        _removeChild__e5.clear();
        
        __e5 = null;
        
        _endPosition__e7 = autogenerated.removeNodes(__e7, _endPosition__e7);
        
      } else if (!_isVisible__e7 && showNow) {
        
        _isVisible__e7 = true;
        
        __e6 = new autogenerated_html.Element.html('<ul class="autocomplete-content">\n              <template id="__e-5" style="display:none"></template>\n            </ul>');
        __e5 = __e6.query('#__e-5');
        __stoppers2_1 = [];
        
        autogenerated.insertAllBefore(__e7.parentNode, __e7.nextNode,
        
        [new autogenerated_html.Text('\n            '), __e6, _endPosition__e7 = new autogenerated_html.Text('\n          ')]);
        
        _endPosition__e5 = __e5;
        __stoppers2_1.add(autogenerated.watchAndInvoke(() => matches, (_) {
          for (var remover in _removeChild__e5) remover();
          _removeChild__e5.clear();
          
          _endPosition__e5 = autogenerated.removeNodes(__e5, _endPosition__e5);
          var __insert___e5 = __e5.nextNode;
          for (var choice in matches) {
            autogenerated_html.LIElement __e4;
            autogenerated_html.EventListener __listener__e4_mouseOver_3_2_1;
            autogenerated_html.EventListener __listener__e4_mouseUp_4_3_2;
            List<autogenerated.WatcherDisposer> __stoppers5_4_3;
            autogenerated_html.DivElement __e3;
            var __binding2;
            __e4 = new autogenerated_html.Element.html('<li class="">\n                  <div id="__e-3"></div>\n                  <!--content select=".choiceTemplate"></content-->\n                </li>');
            __e3 = __e4.query('#__e-3');
            __binding2 = new autogenerated_html.Text('');
            __e3.nodes.add(__binding2);
            __stoppers5_4_3 = [];
            autogenerated.insertAllBefore(__e5.parentNode, __insert___e5,
            [new autogenerated_html.Text('\n                '), __e4, _endPosition__e5 = new autogenerated_html.Text('\n              ')]);
            __listener__e4_mouseOver_3_2_1 = ($event) {
              mouseOverChoice(choice, $event);
              autogenerated.dispatch();
            };
            __e4.on.mouseOver.add(__listener__e4_mouseOver_3_2_1);
            
            __listener__e4_mouseUp_4_3_2 = ($event) {
              selectChoice(choice);
              autogenerated.dispatch();
            };
            __e4.on.mouseUp.add(__listener__e4_mouseUp_4_3_2);
            
            __stoppers5_4_3.add(autogenerated.watchAndInvoke(() =>  choice.key , (__e) { __e4.attributes['choice-key'] = __e.newValue; }));
            __stoppers5_4_3.add(autogenerated.bindCssClasses(__e4, () =>  isFocused(choice) ? 'focused' : 'notfocused' ));
            __stoppers5_4_3.add(autogenerated.watchAndInvoke(() => '${ renderChoice(choice) }', (__e) {
              __binding2 = autogenerated.updateBinding( renderChoice(choice) , __binding2, __e.newValue);
            }));
            _removeChild__e5.add(() {
              (__stoppers5_4_3..forEach((s) => s())).clear();
              __e4.on.mouseOver.remove(__listener__e4_mouseOver_3_2_1);
              __listener__e4_mouseOver_3_2_1 = null;
              
              __e4.on.mouseUp.remove(__listener__e4_mouseUp_4_3_2);
              __listener__e4_mouseUp_4_3_2 = null;
              
              __e4 = null;
              __e3 = null;
              __binding2 = null;
            });
          }
        }));
        
      }
    }));
    
    __listener__e8_blur_6 = ($event) {
      inputBlur($event);
      autogenerated.dispatch();
    };
    __e8.on.blur.add(__listener__e8_blur_6);
    
    __listener__e8_focus_7 = ($event) {
      inputFocus($event);
      autogenerated.dispatch();
    };
    __e8.on.focus.add(__listener__e8_focus_7);
    
    __listener__e8_keyDown_8 = ($event) {
      keyDown($event);
      autogenerated.dispatch();
    };
    __e8.on.keyDown.add(__listener__e8_keyDown_8);
    
    __listener__e8_keyUp_9 = ($event) {
      keyUp($event);
      autogenerated.dispatch();
    };
    __e8.on.keyUp.add(__listener__e8_keyUp_9);
    
  }
  
  void removed_autogenerated() {
    _root = null;
    
    (__stoppers1..forEach((s) => s())).clear();
    
    if (_isVisible__e7) {
      
      _endPosition__e7 = autogenerated.removeNodes(__e7, _endPosition__e7);
      
      __e6 = null;
      (__stoppers2_1..forEach((s) => s())).clear();
      _endPosition__e5 = autogenerated.removeNodes(__e5, _endPosition__e5);
      for (var remover in _removeChild__e5) remover();
      _removeChild__e5.clear();
      
      __e5 = null;
      
    }
    
    __e7 = null;
    
    __e8.on.blur.remove(__listener__e8_blur_6);
    __listener__e8_blur_6 = null;
    
    __e8.on.focus.remove(__listener__e8_focus_7);
    __listener__e8_focus_7 = null;
    
    __e8.on.keyDown.remove(__listener__e8_keyDown_8);
    __listener__e8_keyDown_8 = null;
    
    __e8.on.keyUp.remove(__listener__e8_keyUp_9);
    __listener__e8_keyUp_9 = null;
    
    __e8 = null;
    
  }
  
  void composeChildren() {
    super.composeChildren();
    if (_root is! autogenerated_html.ShadowRoot) _root = this;
  }
  
  /** Original code from the component. */
  
  //  InputAutocompleteComponentProxy.forElement(Element element) : super.forElement(element) {
    //  }
  }
  
